### ISSUE TITLE
Plugin not properly detecting NI PXIe-6341 on Open Ephys v0.5.0

### ISSUE THREAD

**Issue by lachioma** [open-ephys-plugins/nidaq-plugin#5]
Hello
It seems like the plugin does not detect properly my PXIe-6341 on the newest version of Open Ephys v0.5.0, but does work on the older Open Ephys v0.4.6.

Thanks for any help!
Alessandro

with Open Ephys v0.5.0:
![image](https://user-images.githubusercontent.com/29898879/94193807-cf91e180-fe7e-11ea-98a3-742a44ccfb30.png)

with Open Ephys v0.4.6
![image](https://user-images.githubusercontent.com/29898879/94193824-d4569580-fe7e-11ea-88ab-a0393cfd632a.png)

**Comment by anjaldoshi** [comment]
Hi Alessandro,

Thanks for reporting this issue. It is a critical bug that needs to be fixed.

With v0.5.0, we have made some changes in terms of how plugins and their dependencies are loaded, which is the reason behind this issue. As the new Plugin Installer interface needs a special location to download plugins (this is because Plugin Installer doesn't have permission to download files in a path if Open Ephys GUI is installed in a path such as `C:\Program Files\Open Ephys` ), a new DLL search path was added for plugins to find their dependencies. This required a Windows API flag to be enabled to include user-defined paths. Unfortunately, this flag also made the plugins to search for dependencies in `C:\Windows\System32`, which is causing conflicts between the OpenEphys NIDAQ plugin and the nidaqmx dll inside the Window's System32 path. 

I'm looking into this right now, and I'll release a fix for it asap.

**Comment by anjaldoshi** [comment]
This bug has been fixed in the new [v0.5.1 release](https://github.com/open-ephys/plugin-GUI/releases/tag/v0.5.1). Can you please test and confirm this?
Also, if you are using upgrading from v0.5.0 to v0.5.1 using the `open-ephys-v0.5.1-windows.zip` file, delete everything inside `C:\ProgramData\Open Ephys` before upgrading. If you are building the GUI from source or using the Windows Installer, then this step is not required.

**Comment by lachioma** [comment]
Yes, the bug has been fixed. Thank you!
